AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/SingleLineBlockParams:
  Enabled: false
